package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const (
	hyprStart = "-- BEGIN OMARCHY SENSEI (managed by omarchy-sensei setup)"
	hyprEnd   = "-- END OMARCHY SENSEI"
	menuStart = "// BEGIN OMARCHY SENSEI (managed by omarchy-sensei setup)"
	menuEnd   = "// END OMARCHY SENSEI"
)

type CoachedAction struct {
	Action      string
	Title       string
	Shortcut    string
	MenuID      string
	MenuCommand string
}

var coachedActions = []CoachedAction{
	{"screenshot", "Screenshot", "PRINT", "trigger.capture.screenshot", "omarchy-capture-screenshot"},
	{"extract-text-ocr-from-screenshot", "Extract text (OCR) from screenshot", "SUPER + CTRL + PRINT", "trigger.capture.text", "omarchy-capture-text"},
	{"color-picker", "Color picker", "SUPER + PRINT", "trigger.capture.color", "pkill hyprpicker || hyprpicker -a"},
	{"toggle-nightlight", "Toggle nightlight", "SUPER + CTRL + N", "trigger.toggle.nightlight", "omarchy-toggle-nightlight"},
	{"toggle-top-bar", "Toggle top bar", "SUPER + SHIFT + SPACE", "trigger.toggle.top-bar", "omarchy-toggle-bar"},
	{"toggle-workspace-layout", "Toggle workspace layout", "SUPER + L", "trigger.toggle.workspace-layout", "omarchy-hyprland-workspace-layout-toggle"},
	{"toggle-window-gaps", "Toggle window gaps", "SUPER + SHIFT + BACKSPACE", "trigger.toggle.window-gaps", "omarchy-hyprland-window-gaps-toggle"},
	{"lock-system", "Lock system", "SUPER + CTRL + L", "system.lock", "omarchy-system-lock"},
	{"set-reminder", "Set reminder", "SUPER + CTRL + R", "trigger.reminder.set", "omarchy-reminder -i"},
	{"show-reminders", "Show reminders", "SUPER + CTRL + ALT + R", "trigger.reminder.show", "omarchy-reminder show"},
	{"clear-reminders", "Clear reminders", "SUPER + SHIFT + CTRL + R", "trigger.reminder.clear", "omarchy-reminder clear"},
}

func setupIntegration(paths Paths) error {
	if err := installSelf(paths.LocalBinary); err != nil {
		return fmt.Errorf("install collector: %w", err)
	}
	if err := installHyprIntegration(paths); err != nil {
		return fmt.Errorf("install Hyprland integration: %w", err)
	}
	if err := installMenuIntegration(paths); err != nil {
		return fmt.Errorf("install menu integration: %w", err)
	}
	return nil
}

func uninstallIntegration(paths Paths) error {
	if err := removeManagedBlock(paths.HyprlandConfig, hyprStart, hyprEnd); err != nil {
		return err
	}
	if err := removeManagedBlock(paths.MenuExtension, menuStart, menuEnd); err != nil {
		return err
	}
	err := os.Remove(paths.SenseiLua)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return nil
}

func integrationInstalled(paths Paths) bool {
	content, err := os.ReadFile(paths.HyprlandConfig)
	return err == nil && strings.Contains(string(content), hyprStart)
}

func installSelf(destination string) error {
	source, err := os.Executable()
	if err != nil {
		return err
	}
	source, err = filepath.EvalSymlinks(source)
	if err != nil {
		return err
	}
	if source == destination {
		return nil
	}
	data, err := os.ReadFile(source)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(destination), 0o755); err != nil {
		return err
	}
	return writeAtomic(destination, data, 0o755)
}

func installHyprIntegration(paths Paths) error {
	content, err := os.ReadFile(paths.HyprlandConfig)
	if err != nil {
		return err
	}
	clean := stripManagedBlock(string(content), hyprStart, hyprEnd)
	needle := "-- Load Omarchy defaults."
	index := strings.Index(clean, needle)
	if index < 0 {
		return errors.New("could not find the Omarchy defaults marker in hyprland.lua")
	}
	block := hyprStart + "\nrequire(\"default.hypr.helpers\")\nrequire(\"hypr.sensei\")\n" + hyprEnd + "\n\n"
	updated := clean[:index] + block + clean[index:]
	if err := backupAndWrite(paths.HyprlandConfig, []byte(updated), 0o644); err != nil {
		return err
	}
	return writeAtomic(paths.SenseiLua, []byte(senseiLua()), 0o644)
}

func installMenuIntegration(paths Paths) error {
	content, err := os.ReadFile(paths.MenuExtension)
	if errors.Is(err, os.ErrNotExist) {
		content = []byte("{\n}\n")
	} else if err != nil {
		return err
	}
	clean := stripManagedBlock(string(content), menuStart, menuEnd)
	open := strings.Index(clean, "{")
	if open < 0 {
		return errors.New("menu extension is not a JSONC object")
	}
	block := menuOverrideBlock()
	updated := clean[:open+1] + "\n  " + menuStart + "\n" + block + "  " + menuEnd + clean[open+1:]
	return backupAndWrite(paths.MenuExtension, []byte(updated), 0o644)
}

func senseiLua() string {
	var out strings.Builder
	out.WriteString("-- Generated by omarchy-sensei setup. Re-run setup instead of editing this file.\n")
	out.WriteString("if o and not o._sensei_original_bind then\n")
	out.WriteString("  o._sensei_original_bind = o.bind\n")
	out.WriteString("  local coached = {\n")
	for _, action := range coachedActions {
		fmt.Fprintf(&out, "    [%s] = %s,\n", luaQuote(action.Title), luaQuote(action.Action))
	}
	out.WriteString("  }\n\n")
	out.WriteString(`  local function slug(value)
    return tostring(value):lower():gsub("[^%w]+", "-"):gsub("^-", ""):gsub("-$", "")
  end

  local function quote(value)
    return "'" .. tostring(value):gsub("'", "'\\''") .. "'"
  end

  function o.bind(keys, description, dispatcher, options)
    local original = o._sensei_original_bind
    original(keys, description, dispatcher, options)
    local key_text = tostring(keys or "")
    if not description or key_text:find("mouse", 1, true) or key_text:find("switch:", 1, true) then return end

    local action = coached[description] or slug(description)
    local command = "omarchy-sensei record --action " .. quote(action)
      .. " --title " .. quote(description)
      .. " --trigger shortcut --shortcut " .. quote(key_text)
    local record_options = {}
    for key, value in pairs(options or {}) do
      if key ~= "description" and key ~= "mouse" then record_options[key] = value end
    end
    original(keys, nil, command, record_options)
  end
end
`)
	return out.String()
}

func menuOverrideBlock() string {
	var out strings.Builder
	for _, action := range coachedActions {
		if action.MenuID == "" {
			continue
		}
		command := "omarchy-sensei run --action " + shellQuote(action.Action) +
			" --title " + shellQuote(action.Title) +
			" --shortcut " + shellQuote(action.Shortcut) +
			" -- " + shellQuote(action.MenuCommand)
		encodedID, _ := json.Marshal(action.MenuID)
		encodedCommand, _ := json.Marshal(command)
		fmt.Fprintf(&out, "  %s: {\"action\":%s},\n", encodedID, encodedCommand)
	}
	return out.String()
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\\''") + "'"
}

func luaQuote(value string) string {
	return fmt.Sprintf("%q", value)
}

func stripManagedBlock(content, start, end string) string {
	startIndex := strings.Index(content, start)
	if startIndex < 0 {
		return content
	}
	lineStart := strings.LastIndex(content[:startIndex], "\n") + 1
	endIndex := strings.Index(content[startIndex:], end)
	if endIndex < 0 {
		return content
	}
	endIndex += startIndex + len(end)
	if endIndex < len(content) && content[endIndex] == '\n' {
		endIndex++
	}
	return content[:lineStart] + content[endIndex:]
}

func removeManagedBlock(path, start, end string) error {
	content, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	updated := stripManagedBlock(string(content), start, end)
	if updated == string(content) {
		return nil
	}
	return backupAndWrite(path, []byte(updated), 0o644)
}

func backupAndWrite(path string, data []byte, mode os.FileMode) error {
	if current, err := os.ReadFile(path); err == nil && string(current) != string(data) {
		backup := fmt.Sprintf("%s.sensei-backup-%s", path, time.Now().Format("20060102-150405"))
		if err := os.WriteFile(backup, current, mode); err != nil {
			return err
		}
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return writeAtomic(path, data, mode)
}

func writeAtomic(path string, data []byte, mode os.FileMode) error {
	temporary, err := os.CreateTemp(filepath.Dir(path), ".sensei-*")
	if err != nil {
		return err
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if _, err := temporary.Write(data); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Chmod(mode); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	return os.Rename(temporaryPath, path)
}
